uninterrupted-tech/serverless-plugin-webform

.github/.gitmessage, .github/pull_request_template.md
Add git commit message template.
Please mark **one** relevant option:
=> chore: add git commit message template

package-lock.json, package.json
Add repository url to package.json to make it visible in npm. Change version to v0.1.7.
Please mark **one** relevant option:
=> chore: add repository url to package.json

.github/ISSUE_TEMPLATE/technical_improvement.md
Add template for technical improvement issues.
Please mark **one** relevant option:
=> chore: add technical improvement issue template

.github/.gitmessage
Remove issue number from commit message since new configuration adds number of pull request to commit message automaticaly. We will still have information about issue number (if it exists) in pull request description.
Please mark **one** relevant option:
=> chore: remove issue number from commit message

README.md, package.json
* Use Prettier for MD files
* Extends `npm run format` script
=> chore: use prettier for markdown files

.github/.gitmessage, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/technical_improvement.md, .github/pull_request_template.md
Improve GitHub templates:
* Pull Request
* issue
* commit
=> chore: improve GitHub templates

README.md, package-lock.json, package.json
Update README:
* fix installation instructions
* update feature-development section
=> docs: fix installation instructions and update feature-development section in readme

package-lock.json, package.json, src/ses.js
Change the path to root directory.
**Issue:** #23
=> fix: visitor confirmation cannot load

README.md, src/lambda/utils/verifyCaptcha.ts
Add information about cors configuration to readme.
=> docs: add information about cors configuration

package-lock.json, package.json
=> release: v1.0.0

package-lock.json, package.json
=> release: v1.0.1

src/ses.js
Change the identity verification to check verification of an email but also a domain.
**Issue:** #39
=> fix: verification of identities doesn't work correctly

src/lambda/utils/sendMails.ts
When an email notification is received, form owner may want to reply to the visitor directly. This PR adds "reply-to" property what allows to achieve above.
=> feat: reply-to in notification email

README.md, package-lock.json, package.json, src/environments.js, src/lambda/config.ts, src/lambda/createVisitor.ts, src/lambda/logger.ts, src/lambda/utils/sendMails.ts, src/lambda/utils/sendSlackWebhook.ts
=> chore: add pino logger

package-lock.json, package.json
=> release: v1.2.0

src/lambda/utils/sendMails.ts
=> chore: add more logs to notification mail

src/lambda.js
=> fix: fix sls logger

package-lock.json, package.json
=> release: v1.2.1

README.md
Added important section in SES configuration.
=> docs: update ses doc section

package-lock.json, package.json
=> release: v1.2.2
